language: java
sudo: false

cache:
  directories:
  - $HOME/.m2
  
matrix:
  include:
    - env: PROFILES='-P osgi-tests'
      jdk: oraclejdk8
      dist: trusty # Otherwise oraclejdk8 is not found, see https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428
    - env: PROFILES=''
      jdk: openjdk11
    - env: PROFILES=''
      jdk: openjdk12
    - env: PROFILES=''
      jdk: openjdk13
    - env: PROFILES=''
      jdk: openjdk14

script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - mvn clean install -B $PROFILES